### ISSUE TITLE
Dialyzer breaks the contract error at DemoWeb.PageController.snake

### ISSUE THREAD

**Issue by wanton7** [chrismccord/phoenix_live_view_example#13]
I get following Dialyzer warning ```The call 'Elixir.Phoenix.Controller':put_layout(_conn@1::any(),'game') breaks the contract ('Elixir.Plug.Conn':t(),{atom(),binary() | atom()} | binary() | 'false') -> 'Elixir.Plug.Conn':t()```

Caused by `|> put_layout(:game)` in `DemoWeb.PageController.snake`. Type spec for Phoenix.Controller.put_layout doesn't allow second argument be atom.

**Comment by chrismccord** [comment]
The typspec is fixed on phoenix master. Thanks!
