### ISSUE TITLE
Whats the purpose of the user_controller? 

### ISSUE THREAD

**Issue by joshchernoff** [chrismccord/phoenix_live_view_example#14]
Trying to understand why this was added to the demo. I couldn't find if it was being used, so this is more a question than a bug. I assume it's not being used at all. 

https://github.com/chrismccord/phoenix_live_view_example/blob/master/lib/demo_web/controllers/user_controller.ex

**Comment by al2o3cr** [comment]
It's mounted at `/plain/users`:

https://github.com/chrismccord/phoenix_live_view_example/blob/13b07ae9a019fb89511d7f06f4634b992bc64627/lib/demo_web/router.ex#L37

**Comment by chrismccord** [comment]
It's the original generated controller I ran from `mix phx.gen.html`. Not necessary at all :)

**Comment by machineloop** [comment]
Hey @chrismccord, realize this thread is now closed, but curious whether it's possible to gracefully degrade (without JS/socket) the new user form submission to the `/plain/users` UserController?

 I've tried it out a couple different ways, but can't get the form to submit successfully... Thanks!
