### ISSUE TITLE
Image Example showing up at Clock and Counter

### ISSUE THREAD

**Issue by optikfluffel** [chrismccord/phoenix_live_view_example#18]
I'm not sure wether this is intended or not, but the example from `/image` is also showing up at `/clock` and `/counter`. On top of that I also see the clock at `/counter`.
This happens on my local machine (running macOS) and also on [phoenix-live-view-example.gigalixirapp.com](https://phoenix-live-view-example.gigalixirapp.com).

![Screenshot of Firefox showing /clock](https://user-images.githubusercontent.com/379915/54594839-c1fdcf00-4a31-11e9-9378-c4d07719a93a.png)

![Screenshot of Firefox showing /counter](https://user-images.githubusercontent.com/379915/54594892-de9a0700-4a31-11e9-92eb-98a7a0b3e5a2.png)

**Comment by chrismccord** [comment]
Yes, this is me testing/showing dynamically added/removed nested children. A proper example with a real usecase would be better, but it's not an accident :)
