### ISSUE TITLE
Should `Phoenix.HTML.Form.form_for/3` be used when integrating LiveView with forms?

### ISSUE THREAD

**Issue by rickclare** [chrismccord/phoenix_live_view_example#22]
I noticed in the documentation for `Phoenix.HTML.Form`, a suggestion to use `form_for/3` when integrating LiveView with forms. 

i.e from:

https://github.com/phoenixframework/phoenix_html/blob/4826c4dd3b83e86189aae1a6492cd622ddfb1653/lib/phoenix_html/form.ex#L185-L205

```
  ## Phoenix.LiveView integration
  Because `Phoenix.LiveView` is unable to compute diffs inside
  anonymous functions, Phoenix.HTML provides `form_for/3` that works
  without passing an anonymous function. Inside live views, instead of
      <%= form_for @changeset, opts, fn f -> %>
        <%= text_input f, :name %>
      <% end %>
  you would write
      <%= f = form_for @changeset, opts %>
        <%= text_input f, :name %>
      </form>
  In the second case, the `form_for` emits only the opening of the
  `<form>` tag, which then needs to be closed explicitly in HTML.
  Since the anonymous function has been removed, `Phoenix.LiveView`
  is able to optimize forms too. Although outside of live views,
  we recommend using the first construct.
```

However, this suggestion is not applied in the "user form" example, which still uses `form_for/4`:

https://github.com/chrismccord/phoenix_live_view_example/blob/8924b9123054c0f1920d276601f1a4a5748958cd/lib/demo_web/templates/user/form.html.leex#L1

Is this an accidental omission from the "user form" example, or it is no longer necessary to use `form_for/3` to optimize forms for LiveView?

**Comment by chrismccord** [comment]
Please send a PR. Thanks!

**Comment by rickclare** [comment]
PR raised to address this question https://github.com/chrismccord/phoenix_live_view_example/pull/23
