### ISSUE TITLE
Error fetching/updating Git repository

### ISSUE THREAD

**Issue by danfrenette** [chrismccord/phoenix_live_view_example#29]
I'm running off a fresh install of Elixir. `mix -v` returns
```shell
Erlang/OTP 21 [erts-10.3.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Mix 1.8.1 (compiled with Erlang/OTP 21)
```

My issue is that whenever I run `mix deps.get` I get the following error:

```
* Getting phoenix (https://github.com/phoenixframework/phoenix.git)
** (Mix) Error fetching/updating Git repository: the "git" executable is not available in your PATH. Please install Git on this machine or pass --no-deps-check if you want to run a previously built application on a system without Git.
```

Which is really weird because I definitely have git installed. Also adding the `--no-deps-check` flag to the command doesn't change the output. I've looked around for a solution to this but haven't found anything. Any suggestions greatly appreciated! Thanks!

**Comment by chrismccord** [comment]
This doesn't look phoenix or LV related, so this isn't the best place to troubleshoot. Folks on the forums or slack may have some ideas. Thanks!

**Comment by danfrenette** [comment]
@chrismccord I'll check those out, thanks!
