### ISSUE TITLE
leex HTML safety issue

### ISSUE THREAD

**Issue by chrism2671** [chrismccord/phoenix_live_view_example#50]
This is more of a support request, but I've been struggling for a day with this, so thought I'd ask here.

In my `leex` template, when the liveview update gets pushed to the browser, it seems like most of the HTML markup (specifically, `<td>` tags) get stripped from the content.

It isn't clear to me why `leex` templates should be HTML safe, when `eex` ones allow you to render whatever you want.

How should I structure my table rows, where each row is rendered as:

    <%= for row <- @rows do %>
        <%= Phoenix.LiveView.live_render(@conn, ShortrWeb.LinkLive.Index, session: %{} %>
    <% end %>

in an `eex` template.

**Comment by snewcomer** [comment]
@chrism2671 👋 If the `td` tags are getting stripped (I'm assuming this is the undesired part), it might mean there is invalid table html.  (like a `div` in between table elements that shouldn't be there).  When we diff those using native Browser API's, those API's will throw out the `<td>` or other relevant elements that make the table invalid.

Lmk if you have a reproduction or screenshot we can look at!

**Comment by chrism2671** [comment]
They are. I've actually tried pairing it back to just `<tr><td>Hello</td></tr>`, but the same behaviour occurs.
It's plausible there could a broken div somewhere else in the template (e.g. at `app.html.eex`), but I wouldn't expect that to cause an issue here?

![localhost_4000_app_workspace_2_links](https://user-images.githubusercontent.com/456541/69877856-307e7680-12bb-11ea-908d-590441665c86.png)

**Comment by chrism2671** [comment]
Re: the screenshot above, the table at the bottom renders first, and then the stuff above it gets printed once the liveview kicks in.

**Comment by chrism2671** [comment]
OK I think I figured it out. It looks to me like you can't have naked table rows in a leex include.

This:
`<table><tr><td>Hello</td</tr></table>`

Renders fine. But take the `<table>` out and the `<tr>` and `<td>` get stripped.

Is there a way to force LiveView to just render what we tell it?

**Comment by snewcomer** [comment]
I don't think we can.  The HTML5 spec defines what happens when parsing syntactically incorrect document.  Browsers have a certain error tolerance as it relates to invalid HTML as well.

https://html.spec.whatwg.org/multipage/syntax.html#tree-construction
https://html.spec.whatwg.org/multipage/parsing.html#unexpected-markup-in-tables

**Comment by chrism2671** [comment]
Hmm. I guess that means that you definitely can't liverender rows individually; you *must* liverender a full `<table>`.

It might be worth mentioning that in the docs - it's definitely not obvious.

**Comment by chrismccord** [comment]
This is not correct. You can `live_render` with the `container: {:tr, []}` option. By default, `live_render` uses a `div`. You also very likely want to use `live_component` instead, but live_render will work just find rendering table rows. As Scott said, the HTML must be valid or browsers will mangle the markup. Thanks!
