### ISSUE TITLE
no function clause matching in DemoWeb.UserLive.Show.mount/2

### ISSUE THREAD

**Issue by mekostin** [chrismccord/phoenix_live_view_example#51]
1. git clone https://github.com/chrismccord/phoenix_live_view_example.git
2. cd phoenix_live_view_example && mix deps.get && mix deps.compile && cd assets && npm install && cd ../
3. mix ecto.setup
4. mix phx.server
5. http://127.0.0.1:4000/users/1

[info] GET /users/1
[debug] Processing with Phoenix.LiveView.Plug.Elixir.DemoWeb.UserLive.Show/2
  Parameters: %{"id" => "1"}
  Pipelines: [:browser]
[info] Sent 500 in 45ms
[error] #PID<0.537.0> running DemoWeb.Endpoint (connection #PID<0.526.0>, stream id 3) terminated
Server: 127.0.0.1:4000 (http)
Request: GET /users/1
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in DemoWeb.UserLive.Show.mount/2
        (demo) lib/demo_web/live/user_live/show.ex:23: DemoWeb.UserLive.Show.mount(%{}, #Phoenix.LiveView.Socket<assigns: %{}, changed: %{}, endpoint: DemoWeb.Endpoint, id: "phx-zV5TkpFP", parent_pid: nil, view: DemoWeb.UserLive.Show, ...>)
        (phoenix_live_view) lib/phoenix_live_view/view.ex:469: Phoenix.LiveView.View.call_mount!/3
        (phoenix_live_view) lib/phoenix_live_view/view.ex:429: Phoenix.LiveView.View.call_mount_and_handle_params!/6
        (phoenix_live_view) lib/phoenix_live_view/view.ex:302: Phoenix.LiveView.View.static_render/3
        (phoenix_live_view) lib/phoenix_live_view/controller.ex:37: Phoenix.LiveView.Controller.live_render/3
        (phoenix) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
        (demo) lib/demo_web/endpoint.ex:1: DemoWeb.Endpoint.plug_builder_call/2
        (demo) lib/plug/debugger.ex:122: DemoWeb.Endpoint."call (overridable 3)"/2
        (demo) lib/demo_web/endpoint.ex:1: DemoWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:42: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy) /tmp/phoenix_live_view_example/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /tmp/phoenix_live_view_example/deps/cowboy/src/cowboy_stream_h.erl:320: :cowboy_stream_h.execute/3
        (cowboy) /tmp/phoenix_live_view_example/deps/cowboy/src/cowboy_stream_h.erl:302: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

**Comment by snewcomer** [comment]
@mekostin #44  I am going to get the examples working with the latest LV.  This PR is mostly g2g but I plan on also adding tests.

**Comment by mekostin** [comment]
> @mekostin #44 I am going to get the examples working with the latest LV. This PR is mostly g2g but I plan on also adding tests.

OK, it will be great! Because I can't find workable CRUD demos with the latest versions of LV.
