### ISSUE TITLE
Please update for latest 0.9.0 LiveView - really hard to get it working after upgrade

### ISSUE THREAD

**Issue by margusp2heathmont** [chrismccord/phoenix_live_view_example#59]
Working examples welcomed.

**Comment by SebastianStroniewskiWojtczak** [comment]
0.9.0
To get working most of examples:
1) git clone https://github.com/chrismccord/phoenix_live_view_example.git
2) mix deps.get
3) cd deps/phoenix_live_dashboard
apply below patch on mix.exs

> \- {:phoenix_live_view, "~> 0.9.0", phoenix_live_view_opts()}

> \+ {:phoenix_live_view, "~> 0.9.0"}


4) Go back to root directory of your cloned project and apply below patch
4.1) pipeline :browser
>    #plug :put_root_layout, {DemoWeb.LayoutView, :app}
>    plug :put_live_layout, {DemoWeb.LayoutView, :app}

4.2) Comment out rest usage of :put_root_layout
>  #plug :put_root_layout, {DemoWeb.LayoutView, :app}

5) Finally most demos starts working. issue is that "_phoenix_live_dashboard_" uses Master Head of Phoenix LiveView from git, and that one picks 0.9.1 which broke LayoutView. Thats why most demos/examples stopped working and I have no idea how to get them working with 0.9.1

**Comment by SebastianStroniewskiWojtczak** [comment]
I've made a pull request to get examples working with last Phoenix LiveView changes -> 0.9.1

**Comment by josevalim** [comment]
Master should be updated.
