### ISSUE TITLE
Socket assigns params not availabel in render function

### ISSUE THREAD

**Issue by afs091** [chrismccord/phoenix_live_view_example#64]
Hello Chris,

I am trying some LiveView examples and to install it I am followed the instructions in hex (https://hexdocs.pm/phoenix_live_view/installation.html).

I am getting a ArgumentError at GET /welcome when executing this code:

`
 defmodule DemoWeb.WelcomeLive do
    use Phoenix.LiveView

    def render(assigns) do
        ~L"""
        <div>
            <h2><%= @salutation %></h2>
        </div>
        """
    end

    def mount(_session, socket) do
        salutation = "Welcome to LiveView from socket assigns"
        {:ok, assign(socket, salutation: salutation)}
    end
 end
`

ArgumentError at GET /welcome
assign @salutation not available in eex template.

Please make sure all proper assigns have been set. If this
is a child template, ensure assigns are given explicitly by
the parent template as they are not automatically forwarded.

Available assigns: [:flash, :live_action, :live_module, :socket]

Could you help me spot the error?
Thank you in advance for your attention!

**Comment by richardkmichael** [comment]
@afs091 

I had the same problem upgrading from 0.4 to 0.10.  I "fixed" it by adding to `assigns` in `render()`, although I am doubtful this is the correct fix:

```elixir
def render(assigns) do
  assigns = assigns |> Map.put(:salutation, "Welcome")
end
```

If you try this and the error goes away, but then the `mount()` method is not called, I would like to know.  (I am now having that problem.)

**Comment by afs091** [comment]
Hello, the idea is to use assign salutation to socket in mount function. Your solution will "fix" the error but my problem will remain, I need to be able to pass information through socket to have it available between different functions. 

I will try version 0.4, thank you!

**Comment by richardkmichael** [comment]
@afs091 Leave the `mount` function as it is (with the `salutation` assign) and it will be updated.  The problem, I believe, is that on initial render of the template, the `@salutation` assign is not yet available, so adding in `render()` "fixes" it.  This is will not affect the update of the value in the `mount` function.

**Comment by chrismccord** [comment]
Your `mount/2` needs to be `mount/3`, ie `def mount(_session, _params, socket)`

Note that you *do not* want to alter the assigns on `render/1`. You will lose change tracking and it's going to break in unexpected ways.

**Comment by richardkmichael** [comment]
Thanks @chrismccord !

**Comment by afs091** [comment]
Thank you @chrismccord !

It changes, see here **version 0.4.0** -> `mount/2` (https://hexdocs.pm/phoenix_live_view/0.4.0/Phoenix.LiveView.html) and **version 0.10.0** -> `mount/3` (https://hexdocs.pm/phoenix_live_view/0.10.0/Phoenix.LiveView.html)

**Comment by richardkmichael** [comment]
@afs091 I was just about the review the documentation, thanks :)

**Comment by richardkmichael** [comment]
`mount/2` changed to `mount/3` in df744346a8a266e1062466ddece93df07d364c1a, between v0.5 to v0.6; a deprecation mentioned in the [ChangeLog](https://github.com/phoenixframework/phoenix_live_view/blob/v0.6.0/CHANGELOG.md).  I missed this.

The deprecation was removed in v0.10.0, in 28a6d9f6b977e6b02f0c0d7bbb41d396902adfa5.
