### ISSUE TITLE
function NaiveDateTime.local_now/0 is undefined or private

### ISSUE THREAD

**Issue by ghenry** [chrismccord/phoenix_live_view_example#69]
Anyone else get this?

![Screenshot_2020-04-24 UndefinedFunctionError at GET thermostat](https://user-images.githubusercontent.com/159608/80204751-579a6380-8621-11ea-9656-f9b7a4590cd3.png)

**Comment by optikfluffel** [comment]
Are you using an "old" (as in before `1.10.0`) version of Elixir? I think `NaiveDateTime.local_now` was added fairly recently.

**Comment by ghenry** [comment]
Looks like it:

elixir --version
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:12:12] [ds:12:12:10]
[async-threads:1] [hipe]

Elixir 1.9.2 (compiled with Erlang/OTP 22)

but I'm on Fedora 31 latest. Will see about upgrading package.

Thanks.

**Comment by ghenry** [comment]
Sorted. Used precompiled version and all working:

```
elixir --version
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.10.3 (compiled with Erlang/OTP 21)
```
