### ISSUE TITLE
== Compilation error in file lib/demo_web/live/counter_live.ex ==

### ISSUE THREAD

**Issue by karthikg** [chrismccord/phoenix_live_view_example#9]
When I follow the instructions to bring the example. I get the following error. 

== Compilation error in file lib/demo_web/live/counter_live.ex ==
** (CompileError) lib/demo_web/live/counter_live.ex: invalid quoted expression: %{dynamic: [{:=, [], [{:arg0, [], Phoenix.LiveView.Engine}, {{:., [], [Phoenix.LiveView.Engine, :to_safe]}, [], [{:live_render, [line: 15], [{:@, [line: 15], [{:socket, [line: 15], nil}]}, {:__aliases__, [line: 15], [:DemoWeb, :ImageLive]}]}]}]}], static: ["\n", {:arg0, [], Phoenix.LiveView.Engine}, "\n  "], vars_count: 1}
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (elixir) expanding macro: Kernel.if/2
    lib/demo_web/live/counter_live.ex:12: DemoWeb.CounterLive.render/1
    expanding macro: Phoenix.LiveView.sigil_L/2
    lib/demo_web/live/counter_live.ex:5: DemoWeb.CounterLive.render/1
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

**Comment by TheFirstAvenger** [comment]
Unable to reproduce locally. Have you made any changes to the phoenix_live_view_example code, or are you up to date with master? If up to date with master, what version of phoenix_live_view appears in your mix.lock file?

**Comment by karthikg** [comment]
I figured it out. I was running elixir 1.5 .  Once I upgraded to 1.8+ it fixed the errors.
